Deploy to HuggingFace Template
AnswerDotAI/fasthtml-example pull request #1
Opened 2024-06-12 16:33 UTC by freddyaboulton

Add some instructions and scripts to deploy the todos app to huggingface spaces. 

Persistent storage is a paid feature on hugging face, this template will automatically backup the sqlite files a to a huggingface dataset.

2024-06-19 17:10 UTC, jph00 requested changes
Thank you for this - great stuff! BTW best to at-notify me of new PRs/issues so I don't miss them.

Is the dockerfile needed? In the past I've used hf spaces without needing a dockerfile, which was a little simpler. We'd like to use whatever the simplest approach is that works! (And if that's having a dockerfile, that's fine -- just checking...)

2024-06-19 17:10 UTC, jph00 commented on todos2-hf/requirements.txt
> +sqlite_utils
```suggestion

```

This isn't required -- sqlite_minutils is included in fasthtml.

2024-06-24 10:19 UTC, freddyaboulton commented on todos2-hf/requirements.txt
> +sqlite_utils
Removed!

2024-06-24 10:24 UTC, freddyaboulton commented
@jph00 removed sqlite-utils from the requirements file. About the Dockerfile - we could deploy this app using the gradio space template and that would remove the need for the Dockerfile. I thought that'd be confusing though since fasthtml is not gradio. I think down the line it would be nice if there was a built-in fasthtml template for spaces and that would require using the Dockerfile. 

I'll leave it up to you - happy to implement whichever one :)

2024-06-24 21:25 UTC, jph00 commented
Can you explain the dockerfile thing a bit more Freddy? Does it currently
work without the dockerfile? If so, what makes you think it might be
confusing?

A builtin template sounds very interesting. What might that do/contain?
Would it make your example simpler/easier?

> Message ID: ***@***.***>
>

2024-06-25 18:32 UTC, freddyaboulton commented
The Dockerfile is only needed for deploying to spaces. Locally, you can run the `main.py` and it will work as normal. 

All Hugging Face spaces are built from Dockerfiles. It's just that for Gradio/Streamlit spaces, the Dockerfile is abstracted away from the end user. We can remove the Dockerfile from this PR, but then we'd have to deploy FastHTML apps as Gradio applications (reference [here](https://huggingface.co/docs/hub/spaces-sdks-gradio#create-a-new-gradio-space)). Nothing wrong with that but it felt a bit weird since FastHTML is its own framework.

By built-in template, I meant one of the pre-configured framework options available from the space creation screen. Like JupyterLab and Argilla:

![image](https://github.com/AnswerDotAI/fasthtml-example/assets/41651716/f8234f56-6100-466a-abd9-3bfee39773f5)

The Dockerfile would still need to exist in this PR in that case. It would just make getting started with FastHTML on Spaces faster.

2024-06-28 03:29 UTC, merged

2024-06-28 03:31 UTC, jph00 commented
Makes perfect sense - thanks! I agree choosing 'gradio' would be confusing.

Having an SDK option for FastHTML would be super. Anything we can do to make that happen? Should we aim for that for day-1 release? (I'm guessing that'll be ~2 weeks away.)